### ISSUE TITLE
Issue with base_domain_name

### ISSUE THREAD

**Issue by cloudz** [timothymiller/cloudflare-ddns#1]
`Traceback (most recent call last):
  File "cloudflare-ddns.py", line 98, in <module>
    commitRecord(ip)
  File "cloudflare-ddns.py", line 41, in commitRecord
    base_domain_name = response["result"]["name"]
TypeError: 'NoneType' object is not subscriptable
`

When running ./sync, this is the error that pops up. I have quite a few domainnames @ Cloudflare.

**Comment by manitaggarwal** [comment]
I also get the same error, have you found the solution?

**Comment by timothymiller** [comment]
The subdomains entries do not have to include the base domain name. For example, you would use an empty string to update the base domain name.

Additionally, I added notes to the README specifying the recommended way to handle multiple subdomains per IP address is to use CNAME records.

Commit f9d2ccb updates the config.json subdomain examples to reflect how base domain is appended in code.
