### ISSUE TITLE
Assumes Subdomains Exist

### ISSUE THREAD

**Issue by R0NAM1** [timothymiller/cloudflare-ddns#100]
**Describe the bug**
Looking at Cloudflare.py, it seems it relies mostly on the existence of subdomains to update the records, including root records. I've added some basic logic I'll PR that allows people who only are using root domains to change config.json to:
`"subdomains": [],`

**To Reproduce**
Have subdomains as:
```
 "subdomains": [
        "",
       ],
```
2. Run script, errors out with invalid DNS Record, along with the 'name' part of the request blank:
{'type': 'A', 'name': , 'content': '1.1.1.1', 'proxied': False, 'ttl': 300}

**Expected behavior**
With no subdomains listed, I would assume the root domain be updated instead, but the logic did not exist.

**Comment by R0NAM1** [comment]
Pull Request At #101

**Comment by timothymiller** [comment]
This issue has been resolved.
