### ISSUE TITLE
Docker not working for me

### ISSUE THREAD

**Issue by newbie7800** [timothymiller/cloudflare-ddns#11]
Hi there

Thanks for the work in putting this together. I wanted to follow your ddns example and I set up two ddns.example.com records (A and AAAA). I only want the DDNS to point to these records (both are subdomains) (this is your traeffik scenario).  I also set up an edit DNS API Token.  I then tried to edit the config file with this logic, trying to remove the other authentication option. Here is the file below:

  "cloudflare": [
    {
      "authentication": { 
          "api_token": "[my token here]", 
      },
      "zone_id": "[my id here]",
      "subdomains": [
        "",
        "ddns"
      ],
      "proxied": false
    }
  ]
}

When I run the docker (I have the volume config path pointing to my config file) I keep getting this error in the log files:

Starting cloudflare-ddns ... 
Starting cloudflare-ddns ... done
Attaching to cloudflare-ddns
cloudflare-ddns    | Traceback (most recent call last):
cloudflare-ddns    |   File "/cloudflare-ddns.py", line 11, in <module>
cloudflare-ddns    |     config = json.loads(config_file.read())
cloudflare-ddns    |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
cloudflare-ddns    |     return _default_decoder.decode(s)
cloudflare-ddns    |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
cloudflare-ddns    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
cloudflare-ddns    |   File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
cloudflare-ddns    |     obj, end = self.scan_once(s, idx)
cloudflare-ddns    | j**son.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 7 (char 127)**
cloudflare-ddns exited with code 1

Any help in terms of troubleshooting would be appreciated. Thanks

**Comment by alienp4nda** [comment]
Not sure if it’s just a typo with the config you put in this issue.  If that is your actual config then you’re missing the beginning curly bracket.

**Comment by newbie7800** [comment]
Copy and paste mistake. I confirm the first curly is there.

**Comment by alienp4nda** [comment]
Remove the comma after the api_token value.

If you want to test it out and make sure, assuming you have python3 installed, run python3 from the same location as the config.json file.

The below code is a snippet from the cloudflare-dns.py (line 10) file just without the PATH and without assigning the output to a variable.  

````
import json

with open("./config.json") as config_file:
    json.loads(config_file.read()) 
````

**Comment by newbie7800** [comment]
Thanks **@alienp4nda**  a lot for the very fast responses. That really helped.  I already knew python was running properly and that I had the right version.  It was, as is often the case, a question of syntax. The , was the problem.

**@ Timothy** - Thanks again for providing this docker. It would be really great perhaps to show an active example of the config file with each authentication option. I left the comma in the config file because it was in the original example file and I am not familiar with .json syntax so had no idea whether it should be there or not. I always try and follow the example file as closely as possible.  Now I have it up and running and it is doing its job for IPV6 which is for me what I most need :-).  The only issue is that the ip4 addresses do not get updated.  In the log I have this:

Updating record {'type': 'A', 'name': 'ddns', 'content': 'An error occurred with this application.\n\nNO_RESPONSE_FROM_FUNCTION\n', 'proxied': False}
