### ISSUE TITLE
IPv4 address not updated.

### ISSUE THREAD

**Issue by orpheus1120** [timothymiller/cloudflare-ddns#118]
**Describe the bug**
Installed with docker-compose as per documentation on a raspberry pi 4. I have 2 domains and my subdomains are all CNAME pointing to my A records, hence in my config.json I left the subdomain as empty. This is my config.json:

```
{
  "cloudflare": [
    {
      "authentication": {
        "api_token": "xxxxx"
      },
      "zone_id": "qqqqqq",
      "subdomains": ""
    },
    {
      "authentication": {
        "api_token": "xxxxx"
      },
      "zone_id": "wwwwww",
      "subdomains": ""
    }
  ],
  "a": true,
  "aaaa": false,
  "purgeUnknownRecords": false,
  "ttl": 60
}

```
Logs showed "Updating IPv4 (A) records every 60 seconds" which seems to me that everything was fine. However the IPv4 address was not updated at all. I read through previous issues relating to the same subdomain problem but it seemed the problem has not been fixed.

**To Reproduce**
Follow the config.json format as mentioned, leaving the subdomain empty as "subdomains": ""

**Expected behavior**
A record IPV4 should be updated.

I hope I am missing something simple over here. Any help would be greatly appreciated.

**Comment by Afk-82** [comment]
Seems like if you want to update the base domain you should set "subdomains": "@" but not leave it empty as the readme do.

**Comment by orpheus1120** [comment]
I had this figure out awhile back. I had tested several solutions posted but found that the following works perfectly. 

If you want to update just the A record, the subdomain section in the `config.json` should be written as: 

```
      "subdomains": [
        {
          "name": "",
          "proxied": false/true
        }
      ]
```

If you have multiple domains that you wish to update to the same IP, then 

```
  "cloudflare": [
    {
      "authentication": {
          "api_token": "API-KEY-1"
      },
      "zone_id": "ZONE-ID-1",
      "subdomains": [
        {
          "name": "",
          "proxied": false/true
        }
      ]
    },
    {
      "authentication": {
          "api_token": "API-KEY-2"
      },
      "zone_id": "ZONE-ID-2",
      "subdomains": [
        {
          "name": "",
          "proxied": false/true
        }
      ]
    }
```

I am not sure why the readme for this repo has not been updated for clearer explanation even though many had pointed out in the past.
