### ISSUE TITLE
Multiple Domains (zones) Support?

### ISSUE THREAD

**Issue by eihns** [timothymiller/cloudflare-ddns#124]
**Describe the bug**
No documentation on how to add multiple domains (zones)

**To Reproduce**
look for documentation on how to add multiple domains (zones)and dont find anything

**Expected behavior**
you would think under "HOW TO ADD MULTIPLE DOMAINS (zones)" to find a valid config for multiple domains. (zones)

**Screenshots**
<img width="707" alt="image" src="https://user-images.githubusercontent.com/43281991/218424301-fbe498f7-ea0c-4e65-8edc-b60dc397d7e7.png">

Srsly, what is the correct syntax? DOES IT even work?

Ive tried adding multiple of those configs into one, i tried multiple "zones" in one file, while it wont throw an error, it will only update the first...?

**Comment by timothymiller** [comment]
@eihns I added info on how to [enable multiple domain support in the README](https://github.com/timothymiller/cloudflare-ddns#-hosting-multiple-domains-zones-on-the-same-ip).
