### ISSUE TITLE
Any way to customize ip lookup method and dns server?

### ISSUE THREAD

**Issue by ccxuy** [timothymiller/cloudflare-ddns#128]
**Is your feature request related to a problem? Please describe.**
My router at home is somehow blocking 1.1.1.1 and maybe cloudflare server.
The error is:
"🧩 IPv4 not detected via 1.1.1.1, trying 1.0.0.1"

**Describe the solution you'd like**

oznu/cloudflare-ddns may have this feature:
-e DNS_SERVER=10.0.0.2 - Set to the IP address of the DNS server you would like to use. Defaults to 1.1.1.1 otherwise.
-e CRON="@daily" - Set your own custom CRON value before the exec portion. Defaults to every 5 minutes - */5 * * * *.

**Describe alternatives you've considered**
No idea

**Additional context**

**Comment by timothymiller** [comment]
There's an open PR to get the IP4 & 6 from the network interface instead of from an HTTP lookup.

If you'd like to make a PR to accomplish this, id be open to it.
