### ISSUE TITLE
Error reading config.json

### ISSUE THREAD

**Issue by VolcanicMG** [timothymiller/cloudflare-ddns#129]
Hello, for some reason I keep getting an error saying the config.json can't be read. I have the config.json file located within the cloudflareDDNS folder. Am I missing something?
Here is my docker-compose:

```
> version: '3.9'
> services:
>   cloudflare-ddns:
>     image: timothyjmiller/cloudflare-ddns:latest
>     container_name: cloudflare-ddns
>     security_opt:
>       - no-new-privileges:true
>     network_mode: 'host'
>     environment:
>       - PUID=1000
>       - PGID=1000
>     volumes:
>       - /cloudflareDDNS/config.json:/config.json
>     restart: unless-stopped
```

Config.json:
```
> {
>   "cloudflare": [
>     {
>       "authentication": {
>         "api_token": "*Privated*",
>         }
>       },
>       "zone_id": "*Privated*",
>       "subdomains": [
>         {
>           "name": "panel",
>           "proxied": true
>         }
>       ]
>     }
>   ],
>   "a": true,
>   "aaaa": true,
>   "purgeUnknownRecords": false,
>   "ttl": 300
> }
```

**Comment by jpmeijers** [comment]
I just ran into the same error. Busy debugging it now.

**Comment by VolcanicMG** [comment]
Yep your right, I checked for that too since I removed stuff guess that one slipped past my sleepy eyes haha

**Comment by timothymiller** [comment]
Running your config through a JSON linter is a good idea @jpmeijers 

Can you confirm @VolcanicMG if checking your config with a linter helps?

**Comment by VolcanicMG** [comment]
> Running your config through a JSON linter is a good idea @jpmeijers 
> 
> Can you confirm @VolcanicMG if checking your config with a linter helps?

Once I get some free time I'll give it a check. I'm more than positive that was the issue.

**Comment by VolcanicMG** [comment]
> Running your config through a JSON linter is a good idea @jpmeijers
> 
> Can you confirm @VolcanicMG if checking your config with a linter helps?

After running it through the JSON linter, with positive results, I still get the error within the console. Here is the updated config.json

```
> {
> 	"cloudflare": [{
> 		"authentication": {
> 			"api_token": "*private*"
> 		},
> 		"zone_id": "*private*",
> 		"subdomains": [{
> 			"name": "panel",
> 			"proxied": false
> 		}]
> 	}],
> 	"a": true,
> 	"aaaa": true,
> 	"purgeUnknownRecords": false,
> 	"ttl": 300
> }
```

**Comment by Nevah5** [comment]
Hmm weird, I cannot manage to get it to work still. I tried the following things:
1. Linting the JSON file for errors (none found)
2. Running the container as root
3. `chmod +r config.json`

Maybe something has changed between the version I was using before and the current one. This is why you should version pin your images...
