### ISSUE TITLE
Error: NO RESPONSE FROM FUNCTION

### ISSUE THREAD

**Issue by kernitus** [timothymiller/cloudflare-ddns#13]
**Describe the bug**
I don't seem to be able to get the script to work anymore, upon running, for every host added it will print this message:

`Updating record {'type': 'A', 'name': '', 'content': 'An error occurred with this application.\n\nNO_RESPONSE_FROM_FUNCTION\n', 'proxied': False}`

**To Reproduce**
Configure config.json as usual. This issue happens with both api tokens and api keys.

**Expected behavior**
For it to update the DNS records.

**Desktop:**
Raspberry Pi 4

**Comment by timothymiller** [comment]
I tested locally without issues.

From that error, it looks like the API went down momentarily.

**Comment by kernitus** [comment]
Yeah you're right, that it seems to work fine now.
