### ISSUE TITLE
Feature: Zone ID by base domain

### ISSUE THREAD

**Issue by yorickdowne** [timothymiller/cloudflare-ddns#132]
**Describe the solution you'd like**

For easier UX for users of eth-docker, it'd be helpful if they could specify a base domain name instead of a zone ID, and the script would look up the zone ID from that.

**Comment by Garethp** [comment]
It looks like this feature was closed, does that mean that it's been implemented? If so, can you add some config in the README for how to just use the zone name instead of the zoneId? I can't seem to figure out how to configure my setup to use the more user-friendly zone name
