### ISSUE TITLE
support idn 

### ISSUE THREAD

**Issue by MidnightTale** [timothymiller/cloudflare-ddns#142]
**Is your feature request related to a problem? Please describe.**
when run script update is not update exist record on idn domain

**Describe the solution you'd like**
update exist record idn domain

**Additional context**
![image](https://github.com/timothymiller/cloudflare-ddns/assets/125941391/477adb4d-0e2f-4f5d-a3bb-c1232c1f6d44)
raw domain  `xn--42c6bawigis4ea3cd2v7d.com`
encode `มายคราฟออนไลน์.com`

**Comment by timothymiller** [comment]
I love the hyprland desktop environment
