### ISSUE TITLE
Could not route to /client/v4/zones/myZone.xxx, perhaps your object identifier is invalid?

### ISSUE THREAD

**Issue by daliborpuljiz** [timothymiller/cloudflare-ddns#152]
Hi, in my case the container returns the error:
Error sending 'GET' request to 'https://api.cloudflare.com/client/v4/zones/myZone.xxx':

{
 "result": null,
 "success": false,
 "errors": [
  {
   "code": 7003,
   "message": "Could not route to /client/v4/zones/myZone.xxx, perhaps your object identifier is invalid?"
  }
 ],
 "messages": []
}

(myZone.xxx - my zone domain from the Cloudflare panel)

**Comment by pageb018** [comment]
I am having the same issue, what was the solution here?

**Comment by DesertCookie** [comment]
I do get the same error. Any solutions to this?

**Comment by jginternational** [comment]
Just make sure you are not selecting the domain as zone.
Find the zone id in the dashboard overview, in the API section

@DesertCookie @daliborpuljiz
