### ISSUE TITLE
Use Cloudflare Trace Instead of ipify or a self hosted solution

### ISSUE THREAD

**Issue by JKomoroski** [timothymiller/cloudflare-ddns#26]
**Is your feature request related to a problem? Please describe.**
The current implementation checks your server to determine the project's public ipv4 address. If you go away, the request will fail.

**Describe the solution you'd like**
I think we should leverage clouflare's trace feature [https://cloudflare.com/cdn-cgi/trace](https://cloudflare.com/cdn-cgi/trace).
If cloudflare goes away, well so does the entire point of this script, and I suspect cloudflare trace will be a bit more reliable.
While making this change you could also migrate the ipv6 check from ipify to cloudflare trace as well.

**Describe alternatives you've considered**
To make it internally consistent, you could use ipify for both ipv4 and ipv6, but I think depending on a single vendor is a better idea. 

**Additional context**
N/A

**Comment by timothymiller** [comment]
That's a good point. By using Cloudflare Trace, we aren't giving Cloudflare any more information than they already have (by nature of serving the DNS requests).

I will review this solution more in depth tonight & consider making a pull request. If anyone else wants to work on it, I will approve your pull request, unless it causes breaking changes.

**Comment by JKomoroski** [comment]
I'm not muy of a python guy, but if it's not done and I find some time I'll give it a try.

**Comment by timothymiller** [comment]
Implemented in [Pull #27](https://github.com/timothymiller/cloudflare-ddns/pull/27)
