### ISSUE TITLE
Ability to choose on a per subdomain basis the proxy state

### ISSUE THREAD

**Issue by dnglchlk** [timothymiller/cloudflare-ddns#30]
I've got some subdomains attached to my cloudflare account that are dynamically updated using this tool. I have a certain number of them proxied and some of them not for various reasons. Is it possible to have a feature where we can individually chose which subdomain is and isn't proxied or could the same be accomplished by running two of the same instances together with different configs? Any insight and replies are appreciated. Massive thank you from everyone here for making this great tool.

**Comment by timothymiller** [comment]
There is [another docker container out there](https://github.com/tiredofit/docker-traefik-cloudflare-companion) that handles this use case really well.

Cloudflare's free tier doesn't allow wildcard CNAMEs with their proxy enabled. This requires their enterprise tier ($200/month+)

You could handle multiple subdomains with a mixture of proxied and not proxied using multiple instances of [cloudflare-ddns](https://github.com/timothymiller/cloudflare-ddns), but I think the above container fits your use case better, albeit with a little steeper learning curve.
