### ISSUE TITLE
Ability to provide Cloudflare API token as a Docker secret

### ISSUE THREAD

**Issue by markormesher** [timothymiller/cloudflare-ddns#31]
**Is your feature request related to a problem? Please describe.**
At the moment you have to provide your API token within the config file, meaning you can't commit that into any source control system.

**Describe the solution you'd like**
The ability to provide the token directly from Docker secrets. A good example in the wild is how Authelia handles this: https://www.authelia.com/docs/configuration/secrets.html. For every sensitive config key there is a corresponding environment variable that tells the service which file to read a value from.

**Describe alternatives you've considered**
You could treat the whole config file as a Docker secret, but that doesn't solve the source control problem. I also thought about a janky script to edit the config when the container starts up and insert the token, but that would be unstable and would only benefit me rather than all users.

**Additional context**
Happy to work on a PR for this if it would be a welcome contribution.

**Comment by timothymiller** [comment]
Great idea. I've been considering this update for a while.

Originally, cloudflare-ddns was just a python script, then I added Docker support. Docker Secrets support is the next logical step to fully supporting the Docker ecosystem.

I would like the solution to support the legacy config.json method, so existing installations don't break.

If you get some time, please feel free to submit a PR.

**Comment by waynehaffenden** [comment]
+1 for this!

**Comment by timothymiller** [comment]
I added a call to action in the README for those interested in opening a PR.
