### ISSUE TITLE
[Question] Does it make sense to get IPv6 address externally with privacy extensions enabled?

### ISSUE THREAD

**Issue by fagnercarvalho** [timothymiller/cloudflare-ddns#36]
The idea about privacy extensions (RFC 4941) is that temporary addresses would be generated and become deprecated randomly for outbound connections and this is the address that is being picked up by https://[2606:4700:4700::1111]/cdn-cgi/trace. This means that there is a chance that after creating the AAAA record that address could be deprecated and any connections to that address would be refused.

From what I heard the best option would be to get the primary IPv6 address by parsing local commands like `ifconfig` instead.

What could you talk about this?

**Comment by timothymiller** [comment]
This is a valid point. I'm not yet clear on an implementation strategy, but if anyone wants to contribute a pr I will approve it.

**Comment by jfilm** [comment]
I'm not familiar with privacy extensions, but they sound like a good idea. I can look into them.

**Comment by cdalvaro** [comment]
Although I understand the motivation for this issue, I think it is dangerous. Since the interface id is generated with the MAC address of the device.

In fact, I ended up here looking for the opposite direction because my AAAA record is getting the _unique global address_. I just want to use the temporary address and keep it updated frequently.

**Comment by timothymiller** [comment]
@cdalvaro Can you use Cloudflare proxying to protect your unique global IPv6 address?

**Comment by cdalvaro** [comment]
> @cdalvaro Can you use Cloudflare proxying to protect your unique global IPv6 address?

Hi @timothymiller, I'm not using Cloudflare proxying. But apparently, the docker image is not registering now the _unique global address_ but a random one instead.

**Comment by LeLocTai** [comment]
Cloudflare only proxy a very limited number of ports. The right way to do it is to [enable](https://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch06s05.html) privacy extension by default. This way the temporary ipv6 is used for outbound connection, and thus become the one found by this tool.
