### ISSUE TITLE
Script creates new registries on existing entries when IP changes

### ISSUE THREAD

**Issue by jpatriarca** [timothymiller/cloudflare-ddns#37]
**Describe the bug**
Using your script in my UMD Pro or using it standalone on a Ubuntu install, I see that anytime my public IP changes, the '@' records are not updated but a new entry are created for each new IP.

Also, in the logs I see the following logs info:

Updating A & AAAA records every 10 minutes
*Adding new record* {'type': 'A', 'name': ' ', 'content': '*publicIPv4*', 'proxied': True, 'ttl': 120}
*Adding new record* {'type': 'AAAA', 'name': ' ', 'content': '*WAN port PublicIP*', 'proxied': True, 'ttl': 120}

The config.json configuration follows your recommendations, using api_token option for authentication with edit permission in the specific DNS zone that I want to update.

The subdomain configuration is unique and it's for the root registration and it's set up with " " configuration. There are multiple subdomains in the zone that are set up with CNAME configuration.

The tests where done in UDM Pro podman container and also in Ubuntu.

**To Reproduce**
1. Wait for a public IP to change
2. Wait for cloudflare-dns to configure the changes
3. Access Cloudflare admin console for the zone and see duplicated registries for IPv4 and/or IPv6

**Expected behavior**
Expecting the script to update existing A/AAAA configuration for the root domain and not to create new registries for the same configuration. When this happen and in specific conditions due to the DNS configuraiton, I lost access to the public IP. I need to get back to the admin console and delete the duplicated registries.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux / UDM Pro
 - Browser N/A
 - Version 20.04 LTE

**Comment by timothymiller** [comment]
Fixed with https://github.com/timothymiller/cloudflare-ddns/commit/4ffbb98f29d16ef3707545fcf14b5095a19f6052

**Comment by jpatriarca** [comment]
Thank you for the update. Now everything seems to be working and I've detected an error in my config that makes your script to create new entries that should be avoided.

On my initial configuration, config.json was like this on the subdomain section:

"subdomains": [
        " "
      ],

When there is a space instead on a subdomain or empty quotes, your script would try to create new entries on the root domain. If the pulled data are the same, nothing happens, but when IPv4 or IPv6 changes, new root domain entries will be created and the old ones would continue to be there. We can see that your script will create new registrations with a space betweem quotes because the log states "Adding new record" instead of "Updating record". 

Made my mistake because I was using UDM-Pro and Podman (which proved to be difficult) to debug the right config and forgot to keep the space there.

I would suggest that your script should not accept subdomains with one or multiple spaces between quotes and add this info in your documentation.

Also, some config.json examples on how to use only api_token option or api_key/email options for authentication, with focus to explain that to avoid one of the configuration there should be empty quotes and the same for some subdomain examples like:

1. root domain update
2. multiple subdomain updates

Thanks

**Comment by timothymiller** [comment]
This sounds like a good idea. I am unavailable to work on this issue at the moment, but if you or another member from the community makes a pull request, I will be happy to accept it 👍

**Comment by timothymiller** [comment]
[This update](https://github.com/timothymiller/cloudflare-ddns/commit/27ccdd0203d60968d7b6831c8a833101363f9e01) strips prefix and suffix whitespace from the subdomain

Feel free to open another issue if you have more questions or feedback!
