### ISSUE TITLE
Script crashes due to concatenate error in line 155

### ISSUE THREAD

**Issue by merlinschumacher** [timothymiller/cloudflare-ddns#38]
**Describe the bug**
The script crashes in line 155 because it tries to concat a string and an int.  I uses docker to run it.

``` shell
cloudflare-ddns    | Traceback (most recent call last):
cloudflare-ddns    |   File "/cloudflare-ddns.py", line 155, in <module>
cloudflare-ddns    |     print("Updating A & AAAA records every " + delay + " seconds")
cloudflare-ddns    | TypeError: can only concatenate str (not "int") to str
```

**To Reproduce**
create a docker-compose setup.
run the container
the script won't run.

**Expected behavior**
The script to run as expected

**Comment by knaackville** [comment]
Attempting to run on Unifi UDM pro with same error.

**Comment by timothymiller** [comment]
Who unit tests these things before release? 🤣

I'll get a fix out shortly.

**Comment by timothymiller** [comment]
[Resolved](https://github.com/timothymiller/cloudflare-ddns/commit/a816fb6c3fba76e5470f29ed722e3ee35a1eb0bb)
