### ISSUE TITLE
Error "cloudflare-ddns.py: error: argument --repeat: expected one argument"

### ISSUE THREAD

**Issue by merlinschumacher** [timothymiller/cloudflare-ddns#40]
**Describe the bug**
Starting the docker container yields the following error for me:
```
usage: cloudflare-ddns.py [-h] [--repeat REPEAT] [--config-path CONFIG]
cloudflare-ddns.py: error: argument --repeat: expected one argument
```

**To Reproduce**
1. run docker container
2. check logs

**Additional context**
Changing the containers command in a compose file to 
```
command: ["python", "-u", "/cloudflare-ddns.py", "--repeat", "300"]
```
fixes the issue

**Comment by timothymiller** [comment]
Awesome work!

I recently merged another PR from the community that changed the way params work to better support Kubernetes deployments.

The community thanks you.
