### ISSUE TITLE
Update Interval Support in config.json

### ISSUE THREAD

**Issue by thecreativeone91** [timothymiller/cloudflare-ddns#43]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to change the update times for the entry in the config.json file so for example the one I'm using I want it to update more often in the case of a WAN failover even than the default 10 min. 
**Describe the solution you'd like**
Variable for the update interval in config.json

**Comment by timothymiller** [comment]
It would make the most sense to trigger a call to this script whenever your WAN failover is triggered, that way there is no delay.

I am hesitant to add variables to config.json because it is the largest barrier to entry for new users.

**Comment by thecreativeone91** [comment]
I'll have to fork it then, It's very unusual to have something like that hardcoded.

**Comment by timothymiller** [comment]
If you make a PR, I will review it.
