### ISSUE TITLE
IP Change causes duplicate DNS entry

### ISSUE THREAD

**Issue by thecreativeone91** [timothymiller/cloudflare-ddns#44]
When updating for an IP address change, it seems rather than replacing the IP on the current A record like DNSTube was doing, this is adding an A record with each IP so it's possible it can resolve to any of them. 

![image](https://user-images.githubusercontent.com/66484981/110968895-0fae2900-8326-11eb-9c8f-b76383bec0bb.png)

**Comment by thecreativeone91** [comment]
I re-configured it and removed all current A records just to test and when the IP changes it still does the same with two entries and the old is not removed.

**Comment by timothymiller** [comment]
Thank you for reporting this. I am investigating.

**Comment by thecreativeone91** [comment]
> Thank you for reporting this. I am investigating.

No Problem. I don't think it matters as it's just running the docker container at startup but I am running it using the UDM Pro https://github.com/boostchicken/udm-utilities/tree/master/cloudflare-ddns

**Comment by timothymiller** [comment]
I wasn't aware a member of our community had packaged this program for udm-utilities! That's awesome!

Docker/legacy mode, it shouldn't matter. I will get this fixed shortly!

**Comment by timothymiller** [comment]
I cannot reproduce this error. Can you re-pull the latest version from DockerHub for me?

**Comment by timothymiller** [comment]
I have had multiple member of the community test for this issue with the latest script, and no issues were found.

**Comment by thecreativeone91** [comment]
The Duplicate entry is caused by using the FQDN for the subdomain, you use the host only for the subdomain it updates properly.

**Comment by timothymiller** [comment]
<img width="1217" alt="Screen Shot 2021-03-12 at 15 59 06" src="https://user-images.githubusercontent.com/46549361/110997825-f28c5100-834b-11eb-8e43-697e9ec77e1a.png">

Can you confirm you are using the latest version?

`docker-compose down`

Then run 

`docker-compose up -d`

We have tested this extensively on the Discord.
