### ISSUE TITLE
Configuration to enable updating of IPv6 or IPv4 only

### ISSUE THREAD

**Issue by lisotton** [timothymiller/cloudflare-ddns#45]
**Is your feature request related to a problem? Please describe.**
I use a provider in Belgium that in their router I don't have option to configure port forwarding for IPv6 addresses. So when I have the AAAA record created, sometime I can connect with my NextCloud running in my Raspberry Pi and sometimes not. 

**Describe the solution you'd like**
I propose to have a configuration to disable the update of IPv6 of IPv4 for a domain in config.json

**Describe alternatives you've considered**
As an alternative now I remove the like in `docker-compose.yml` that configure the network mode as `host`.

**Comment by timothymiller** [comment]
This sounds like a champion idea! I will begin work on adding this feature. Open source wins again!

**Comment by timothymiller** [comment]
Added in [#90](https://github.com/timothymiller/cloudflare-ddns/commit/bdf8c75cadffc636b43fbdb4cdc1987ae3eb5215)

See the updated README section on disabling IPv4 or IPv6.
