### ISSUE TITLE
start-sync.sh deleted all my A and AAAA records

### ISSUE THREAD

**Issue by mikekasprzak** [timothymiller/cloudflare-ddns#47]
This might be user error, but if this sort of destruction was way too easy to trigger.

I have a very simple `config.json` running at two sites.

```
{
  "cloudflare": [
    {
      "authentication": {
          "api_token": "***************************************************"
      },
      "zone_id": "********************************************",
      "subdomains": [
        "home"
      ],
      "proxied": false,
      "ttl": 120
    }
  ]
}
```
Site one (`home`) has no problems, and it works as expected, updating the single `home` subdomain A record. Site two (`work`) decided all my A and AAAA records were stale and must be destroyed. 🔥 

Again the only difference between the two configs was the subdomain was `home` vs `work`. The same API token and zone IDs were used, and the token is only for the specified zone.

Output from the great purge is as follows.

> root@orangepione:~/cloudflare-ddns# ./start-sync.sh
> Requirement already satisfied (use --upgrade to upgrade): requests in ./venv/lib/python3.5/site-packages
> Requirement already satisfied (use --upgrade to upgrade): idna<3,>=2.5 in ./venv/lib/python3.5/site-packages (from requests)
> Requirement already satisfied (use --upgrade to upgrade): urllib3<1.27,>=1.21.1 in ./venv/lib/python3.5/site-packages (from requests)
> Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in ./venv/lib/python3.5/site-packages (from requests)
> Requirement already satisfied (use --upgrade to upgrade): chardet<5,>=3.0.2 in ./venv/lib/python3.5/site-packages (from requests)
> You are using pip version 8.1.1, however version 21.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ⚙️ Individually disable IPv4 or IPv6 with new config.json options. Read more about it here:  https://github.com/timothymiller/cloudflare-ddns/blob/master/README.md
> 🧩 IPv4 not detected
> 🗑️ Deleted stale record 7824af031ca41433b6b2************
> 🗑️ Deleted stale record 1a27989afdb51c6754e2************
> 🗑️ Deleted stale record 8ba9e3afb5f1d77e3df8c************
> 🗑️ Deleted stale record 18b7a2e427866c66081252************
> 🗑️ Deleted stale record 278142ebceeaa2f24173957************
> 🗑️ Deleted stale record cc0c93ecb89a941f933f336************
> 🗑️ Deleted stale record 24a8a854f1f2195dd2abb4f************
> 🗑️ Deleted stale record 5ad62c21350fb73da7ee************
> 🗑️ Deleted stale record be1e9864eccfdc7c2e49e************
> 🗑️ Deleted stale record aa7eee7c35bfe7650d609************
> 🗑️ Deleted stale record b6dfa25f71065ec732bfbf************
> 🧩 IPv6 not detected
> 🗑️ Deleted stale record f281e92f333c99113a4f3************

Since then I moved the script and config to a Raspberry Pi 4, so I don't get the same errors above, but it still destroys any A or AAAA records I add.

Please help! How do I stop it from destroying my records!

And yes, the version that destroys my records was downloaded today. The one that works fine was downloaded a few months ago.

**Comment by timothymiller** [comment]
Please include all your subdomains inside config.json, or use CNAMEs to direct to your authoritative IP address.

**Comment by timothymiller** [comment]
To stop the rogue deleting of your records, I think it should be default behavior of the script to only attempt deleting stale records for domains intersecting the subdomain specified in config.json

**Comment by timothymiller** [comment]
It sounds like there is overwhelming consensus DDNS should not delete other records within that same zone except for domains specified in config.json.

I will personally work on getting this out today.

**Comment by mikekasprzak** [comment]
Thank you Timothy!

**Comment by paulg1981** [comment]
Much appreciated!

**Comment by paulg1981** [comment]
Any word on this? I’ve updated the docker image but still am getting deleted A records for records the script doesn’t update.

**Comment by chuckmckinnon** [comment]
Thanks Timothy. This is otherwise an excellent utility, and I'm grateful to you for making it. Chiming in here with some context about my own use case.

I have a VPS hosting most services on a static IP, and a Raspberry Pi 4 at home hosting a handful of services (Wireguard endpoint, Unifi controller, etc.). At Cloudflare, I have one A record for example.com pointing to the VPS, with a corresponding CNAME record so that *.example.com aliases to example.com. 

I have a second A record for ddns.example.com pointing to the RPi4 at home, with a CNAME record for *.ddns to alias to ddns.example.com. It's a simple config that works really well: anyrandomsubdomain.example.com points to the VPS, but subdomain.ddns.example.com points to the Raspberry Pi. (Traefik and Let's Encrypt make the rest of the magic work.)

My cloudflare-ddns instance is configured to update the ddns subdomain only. Unfortunately, today it erased the main A record for the base domain, example.com. I host other domains on the same VPS and they were unaffected, which led me to suspect cloudflare-ddns since I had just updated and restarted it, which led me here.

Again, despite today's issue, this is a free utility that I very much appreciate. I hope this context helps clarify why I prefer that cloudflare-ddns update only the subdomains specified in the config.

**Comment by racerxdl** [comment]
Same here, just woke up today with all my dns entries deleted except the one updated by cloudflare ddns
![image](https://user-images.githubusercontent.com/578310/113485021-e181bc00-9481-11eb-9946-261b68975a43.png)

**Comment by caiovitord** [comment]
Hi guys, I'm having this same issue.  I also agree that DDNS should not delete other records within that same zone except for domains specified in config.json.

Thanks timothymiller for considering to change this. I appreciate this very much!

**Comment by nico9julio** [comment]
Hello! I have the same issue. I have a domain that is in production and it has my sites, my own nameserver and some client website. I had the great idea to make a subdomain for my home server... the script deleted all my A records :(
Attached the cloudflare log for the API changes.
I think it should only has changed atom.example.com with this config.
By the way, this is my actual config:

{
  "cloudflare": [
    {
      "authentication": {
          "api_token": "111111111111111111111111111111111111111",
          "api_key": {
              "api_key": "1111111111111111111111111111111111111",
              "account_email": "mail@example.com
[auditlog.xlsx](https://github.com/timothymiller/cloudflare-ddns/files/6336921/auditlog.xlsx)

"
                }
      },
      "zone_id": "111111111111111111111111111",
      "subdomains": [
        "atom"
      ],
      "proxied": false
    }
  ],
  "a": true,
  "aaaa": false
}

**Comment by meowtech** [comment]
Same thing happened to me... All of my A and AAAA records are gone.

**Comment by matbor** [comment]
+1 for me.

an option in the config file would be awesome.

**Comment by omeganot** [comment]
I didn't run into this issue, but added a config check in the pull request just above

**Comment by favonia** [comment]
I have been using this great tool but was then bothered by this issue. While waiting for a fix, I implemented my own version in case anyone is interested: https://github.com/favonia/cloudflare-ddns-go.

**Comment by james7132** [comment]
I also just ran into this issue. Has this been resolved yet?
