### ISSUE TITLE
reduce unimportant logging?

### ISSUE THREAD

**Issue by larham** [timothymiller/cloudflare-ddns#48]
Thanks for the ddns scripting. It worked the first time!

Please consider the verbosity of the current logging. At bottom is what I see on the second and subsequent runs, when no DNS change is made.  (In this logging, the WARNING at bottom is on stderr, while the rest is on stdout.)

Instead, I'd like to see output which is relatively quiet if nothing is changed. This would help the current, nice output "Updating record" logging be noticeable when there is a change, or notice real errors when they might appear.

Can you control the pip version and the python libraries as part of the docker scripting? Can you reduce this logging which seems like just noise, and/or make the warning go away with an upgrade or other means?

Thanks for considering this, and providing this useful tool.

Larry

```
$ ./start-sync.sh
Requirement already satisfied: requests in ./venv/lib/python3.7/site-packages (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.7/site-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests) (4.0.0)
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by timothymiller** [comment]
Consider updating your pip install?

In all seriousness, you bring up a valid concern, and I will add some extra logic to the install step to hide the 'Requirement already satisfied' errors.
