### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by kdpuvvadi** [timothymiller/cloudflare-ddns#54]
**Describe the bug**
PyYAML yaml.load(input) Deprecation

**To Reproduce**
1. Go to 

`python3 cloudflare_ddns.py config.yaml`

**Expected behavior**

Update the DNS records

**Screenshots**
![image](https://user-images.githubusercontent.com/7326255/115762425-161dcf00-a3c1-11eb-9ea4-7ed32663e2a2.png)

**Desktop (please complete the following information):**
 - OS: Raspbian 
 - Version 10

**Comment by timothymiller** [comment]
I think this `yaml` warning is not caused by the `cloudflare_ddns.py` script. We do not load yaml files inside the script.

If I am mistaken, feel free to reopen the issue.
