### ISSUE TITLE
Duplicate subdomain entry when IP change.

### ISSUE THREAD

**Issue by Charon-3** [timothymiller/cloudflare-ddns#58]
This happened both ipv4 and ipv6
1. Clone this repo
2. Copy config-example.json to config.json 
2. Config in config.json to change IP at subdomain.domain.com, Remove the first `"",` line in the subdomain array.(Since I don't want to change IP of the domain.com)
3. Run the script

**Expected behavior**
The script will detect old IP from subdomain.domain.com and change the IP in subdomain.domain.com record to the new one.

**Actual behavior**
The script creates another record for subdomain.domain.com.

**Comment by itsmeimtom** [comment]
I was able to "solve" this by changing it from a FQDN to just the intended subdomain in the config. ie: "ddns.example.com" would just become "ddns"  
Just make sure your token is only valid for the specific domain/zone.

Would still be nice to see this fixed though, had me stumped for a bit.

**Comment by timothymiller** [comment]
Good point @itsmeimtom 

I think this is best solved by adding a note to the documentation.
