### ISSUE TITLE
Base Domain Name Issue

### ISSUE THREAD

**Issue by matthewthowells** [timothymiller/cloudflare-ddns#6]
I see others have had issues with the base domain name error, but I don't appear to be getting any closer to a resolution.
I keep getting this error:
```
Checking A records
Traceback (most recent call last):
File "cloudflare-ddns.py", line 104, in <module>
commitRecord(ip)
File "cloudflare-ddns.py", line 41, in commitRecord
base_domain_name = response["result"]["name"]
TypeError: 'NoneType' object is not subscriptable
```

(I've changed subdomain names for security)
I'm trying to update a subdomain, say "ddns" on the domain 37hrd.uk, to my home IP address. Whatever I enter to the subdomains section of the config file results in the error above. On Cloudflare, ddns is an A record, and there are many other A, AAAA, CNAME, MX and TXT records pointing to different places.

Here's the config.json I've been trying to get working:
```
"api_key": "60eNy... redacted",
"account_email": "my email within quotes, it does contain a + plus symbol",
"zone_id": "6cc6c... redacted",
"subdomains": [
(indent) "ddns"
],
"proxied": false
```

I've tried ddns.37hrd.uk, ddns, removing the array and changing the proxied value. Any help would be gratefully appreciated, if I can get this to work, this is 100% going to be the best DDNS solution I've ever tried!

**Comment by matthewthowells** [comment]
I've decided to use another script which does the job, it may be that I was using a custom API key and not the global API key of my account. I did also try "ddns." before deleting but didn't work. Closing issue as no longer relevant to me.

**Comment by timothymiller** [comment]
"the best DDNS solution I've ever tried" to "no longer relevant to me" within 2 days. What a bitch.

**Comment by matthewthowells** [comment]
Yep, sorry! 😂 I'm new to all this but found a script that seemed to just work. No offence to you! If it fails, I will be coming back here don't worry, just I didn't give it enough time in the time I tried it.
