### ISSUE TITLE
Custom interval for DNS updating

### ISSUE THREAD

**Issue by PrecociouslyDigital** [timothymiller/cloudflare-ddns#63]
**Is your feature request related to a problem? Please describe.**
I love how simple and easy this image makes updating my DNS records on cloudflare, but I'd like to configure the frequency at which the DNS records are updated

**Describe the solution you'd like**
I'd like an option in the configuration file that allows a custom interval between DNS updates.

**Describe alternatives you've considered**
Manually editing the container to enable this feature is either very clunky or diverges from upstream very quickly. Orchestrating the container's lifecycle with another service would also be a solution, but right now the container does not run in a one-off context.

**Comment by timothymiller** [comment]
I believe PR #53 helps address this use case.

If you want to run this in a one-off context, start the docker container, wait 10-15 seconds, then stop the docker container.
