### ISSUE TITLE
error reading config.json

### ISSUE THREAD

**Issue by Kentakoong** [timothymiller/cloudflare-ddns#69]
**Describe the bug**
I cloned the project, edited just the subdomains and the credentials, the docker logs as 😡 Error reading config.json

**To Reproduce**
Clone the project, edit subdomains and credentials. 
run ./docker-build.sh
docker run -d {image id}

**Expected behavior**
would run normally

**Screenshots**
![image](https://user-images.githubusercontent.com/35761701/141294471-4d7752ce-926a-49f1-8a81-e036acc5f410.png)
![image](https://user-images.githubusercontent.com/35761701/141293699-9eb75180-20ee-48d1-9178-86f6252ad4a3.png)
![image](https://user-images.githubusercontent.com/35761701/141293457-bbebb16d-f3b8-42ba-92db-6257375c506a.png)

My config file : 
![image](https://user-images.githubusercontent.com/35761701/141295078-79999b92-8343-40ed-ac7a-547c8b631baa.png)

**Desktop (please complete the following information):**
Edited on : 
 - OS: Windows
 - Version 11
Ran On :
 - OS: Ubuntu Server
 - Version 20.04

**Additional context**

**Comment by Kentakoong** [comment]
Resolved : I use docker-compose up -d instead.

**Comment by timothymiller** [comment]
Someone didn't read the documentation 👨‍💻
