### ISSUE TITLE
Script not running with crontab

### ISSUE THREAD

**Issue by Townie-au** [timothymiller/cloudflare-ddns#74]
**Describe the bug**
Crontab not running script. Ubuntu 20.0.0.4

**To Reproduce**
Running ./start-sync.sh with crontab doesn't run python script with message error in screenshot.

Error: [Errno 13] Permission denied: '/home/andrew/venv/pyvenv.cfg'

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'r equirements.txt' Traceback (most recent call last): File "cloudflare-ddns.py", line 17, in <module>

import requests

ModuleNotFoundError: No module named 'requests'

**Expected behavior**
Crontab to run script

**Screenshots**
If applicable, add screenshots to help explain your problem
Hi
I can't get crontab to run the script Ubuntu 20.0.4

**Comment by Townie-au** [comment]
![Uploading Screenshot_20220223-213232.png…]()

**Comment by Bagus-Septianto** [comment]
me too.

but i changed my start-sync.sh from 
```bash
#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

python3 -m venv venv
source ./venv/bin/activate

set -o pipefail; pip install -r requirements.txt | { grep -v "already satisfied" || :; }

cd $DIR
python3 cloudflare-ddns.py
```
to 
```bash
#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

python3 -m venv venv
source ./venv/bin/activate

cd $DIR
set -o pipefail; pip install -r requirements.txt | { grep -v "already satisfied" || :; }
python3 cloudflare-ddns.py
```
and it works fine now

**Comment by timothymiller** [comment]
This issue has been resolved.
