### ISSUE TITLE
Feature Request: Ability to choose on a per subdomain basis the proxy state

### ISSUE THREAD

**Issue by TheFiZi** [timothymiller/cloudflare-ddns#77]
**Is your feature request related to a problem? Please describe.**
I saw this was asked about a year ago via https://github.com/timothymiller/cloudflare-ddns/issues/30 but it wasn't in the feature request format. My hope is you'll reconsider adding this feature.

**Describe the solution you'd like**
I'd like to be able to specify whether a subdomain entry is proxied or not when updated.

**Describe alternatives you've considered**
I reviewed issue 30 and do not want to deploy Traefik at this time to handle a single subdomain in my case. I am going to setup a second instance of cloudflare-ddns per your other suggestion for the time being but it would be nice to only have to maintain one copy.

**Additional context**
I have a few subdomains where I need to leave proxying disabled for the service to function properly. I have a subdomain configured as a A Record that is a random string of characters and a few CNAMES pointing to it for the services that need a direct connection. An attacker could find them if they dug but for someone looking for low hanging fruit they'd probably pass by. I realize it's a security through obscurity thing but unfortunately its my only choice for these services for now.

**Comment by luispflamminger** [comment]
Would also love this!

**Comment by timothymiller** [comment]
I can see a use case for this as well. I'll keep this open if anyone wants to get to it before I do.

**Comment by jgkawell** [comment]
@TheFiZi @timothymiller I've created a PR to add this feature: #86

**Comment by timothymiller** [comment]
This issue has been resolved.
