### ISSUE TITLE
IPv6 address (lan) required to update the WAN IPv6

### ISSUE THREAD

**Issue by opswhisperer** [timothymiller/cloudflare-ddns#78]
**Describe the bug**
The script wont update AAAA unless the host running the script has a valid IPv6 address. If you're querying an external API to retrieve the address then you should be able to do this over IPv4

**To Reproduce**
1. Setup & run the docker container on a bridge network
2. WAN has valid IPv6
3. Script says "IPv6 not detected"
4. Run the container on the host network (host has valid ipv6) and it works

**Expected behavior**
I should be able to update the AAAA record based on the external IPv6 address regardless of the stack running the updater.

**Comment by timothymiller** [comment]
> you should be able to do query IPv6 address over IPv4

You have been misled. You need IPv6 connectivity to get your public IPv6 address.
