### ISSUE TITLE
Inconsistent naming for starter script

### ISSUE THREAD

**Issue by zhanghan177** [timothymiller/cloudflare-ddns#8]
In one of your latest commits, you've changed the starter script from `sync` to `start-sync.sh`. I agree with this change as it makes the main script more straightforward. However, for newcomers, this may cause confusion since you haven't updated the Getting Started script in README. Do you want to take a look at that and reorganize your tool to be more accessible? 

Line: https://github.com/timothymiller/cloudflare-ddns/blob/master/README.md#running-running

**Comment by timothymiller** [comment]
Resolved in [commit a1e1348214dec979fbde6dd2babb54a062df2a82](https://github.com/timothymiller/cloudflare-ddns/commit/a1e1348214dec979fbde6dd2babb54a062df2a82)
