### ISSUE TITLE
Allow not to delete obsolete entries

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [timothymiller/cloudflare-ddns#87]
As seen in https://github.com/timothymiller/cloudflare-ddns/blob/a9d25c743a2341a37e77f79abcbdb9a900528f92/cloudflare-ddns.py#L31 , unused DNS record pointing to other IPs are deleted. In our use case, we actually like to have other DNS records too. I would like to introduce a flag like `ignore_records: array` containing a list of records to ignore in case they point to different IPs.

**Comment by timothymiller** [comment]
This issue has been resolved.
