### ISSUE TITLE
IPv4 Address retrieval doesn't work

### ISSUE THREAD

**Issue by tyalie** [timothymiller/cloudflare-ddns#88]
Hear me out because you'll hate this. For me the IP address 1.1.1.1 doesn't work. All requests to it's ports per UDP or TCP just time out (ping and trace works thoo). This seems to be an issue with my ISP and I've no idea how to fix it. 

On the bright side the cloudflare IPv6 and 1.0.0.1 alternative work perfectly. Would it be possible to configure secure the IP retrieval by adding the cloudflare fallback IPs?

**Comment by timothymiller** [comment]
This issue has been resolved. Lookup address changed to cloudflare.com
