### ISSUE TITLE
Reduce or allow configuration of record TTL

### ISSUE THREAD

**Issue by Technoguyfication** [timothymiller/cloudflare-ddns#89]
**Is your feature request related to a problem? Please describe.**
Potentially, a problem could arise from a < 5 min gap in service availability between IP changes

**Describe the solution you'd like**
Lower record TTL to 1 minute or (preferably) allow configurable record TTL using the JSON config file

**Describe alternatives you've considered**
Manually changing TTL in cloudflare, but I believe the script will overwrite it each time

The current record TTL is hardcoded at 300 seconds, or 5 minutes. This means services could potentially be unavailable for up to 5 minutes between IP changes. I suggest a configuration option is added to allow configurable TTL, to support use cases where a higher or lower TTL would be more appropriate.

**Comment by timothymiller** [comment]
I added the relevant documentation for this to the README.
