### ISSUE TITLE
The root domain record is no longer updated (CF Error 9000: DNS name is invalid)

### ISSUE THREAD

**Issue by notssh** [timothymiller/cloudflare-ddns#91]
**Describe the bug**
As a result of the script execution, only subdomains are updated. When trying to update the root domain record, it gives an error 9000: "DNS name is invalid".
Until about the end of June, everything worked properly. Not now.

**To Reproduce**
1. Edit the config, also add "" to subdomains.
2. Run script

**Expected behavior**
The root domain record must also be updated.

**Additional context**
I tried to change the tokens and the authorization method. It still throws an error only on the root domain.
However, it seems I was able to solve the problem with a small edit of the script. I  changed the value of the variable "name" from subdomain to fqdn. With these edits, everything works as it should again. I can assume that Cloudflare made minor edits to the API, and now an empty domain name is not accepted (previously, the root record was updated under this condition, as I understand it), and now you always need to specify the full one.

**Comment by timothymiller** [comment]
This is an interesting bug to be sure.

Do you mind opening a PR with your fixes?

**Comment by notssh** [comment]
Okay, I'll do it a little later.

**Comment by RutgerP** [comment]
Got the same issue with error 9000 and "" subdomain.

**Comment by varl** [comment]
I am experiencing the same issue, going off the docs[1] I thought that using `"@"` over `""` would solve it, but I got duplicate entries in the Cloudflare management UI.

[1] https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

**Comment by ReFleXzZ** [comment]
Having the same issue here. I'm not sure though, when it started misfunctioning. I think just some couple of days ago. Out of nowhere. If I get access to the logs, I will append them to my comment!

**Comment by rleer** [comment]
The merge request #95 fixed the issue for me

**Comment by lanwatch** [comment]
#96 works for me

**Comment by mojo333** [comment]
@timothymiller is there a plan to merge these PRs and publish an updated Docker container?

**Comment by timothymiller** [comment]
This issue has been resolved.
