### ISSUE TITLE
deleteEntries function does not work correctly.

### ISSUE THREAD

**Issue by notssh** [timothymiller/cloudflare-ddns#97]
**Describe the bug**
Due to incorrect placement of the code block in the deleteEntries function it does not work correctly. It removes records only from the last domain zone in the list.

**To Reproduce**
1. Edit the config, also enable the purgeUnknownRecords option and add two or more Cloudflare configs.
2. Run script.

**Expected behavior**
Existing records from all zones must be deleted.

**Comment by timothymiller** [comment]
This issue has been resolved.
